apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: nidhi9521/notification
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: rxshop
            - name: MONGO_URI
              # value: mongodb://marketplace-mongo-srv:27017/notification
              value: mongodb+srv://nidhi:Nidhi%400905@nasa.uvkxz6f.mongodb.net/notification?tls=true&tlsInsecure=true
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: notification-srv
spec:
  type: NodePort
  selector:
    app: notification
  ports:
    - name: notification
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30709
      
