apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: nidhi9521/store
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: rxshop
            - name: MONGO_URI
              # value: mongodb://marketplace-mongo-srv:27017/store
              value: mongodb+srv://nidhi:Nidhi%400905@nasa.uvkxz6f.mongodb.net/store?tls=true&tlsInsecure=true
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: store-srv
spec:
  type: NodePort
  selector:
    app: store
  ports:
    - name: store
      protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 30712
